server:
  port: 8080
  ssl:
    enabled: false

spring:
  application:
    name: identity-service
  security:
    oauth2:
      client:
        registration:
          google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}
              scope:
                - profile
                - email
              redirect-uri: "{baseUrl}/login/oauth2/code/google"
              client-name: Google
              authorization-grant-type: authorization_code
              client-authentication-method: basic
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: GitHub
            authorization-grant-type: authorization_code
            client-authentication-method: basic
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: id

cors:
  allowed-origins:
    - "http://localhost:3000"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed-headers:
    - "Content-Type"
    - "Authorization"
  allow-credentials: true
  max-age: 3600
