spring:
  application:
    name: common-service

cors:
  allowed-origins:
    - "http://localhost:3000"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed-headers:
    - "Content-Type"
    - "Authorization"
  allow-credentials: true
  max-age: 3600
