version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    hostname: ${POSTGRES_HOST}
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - spring-cloud-network

  pyadmin:
    image: dpage/pgadmin4:2024-10-19-2
    container_name: pyadmin
    hostname: pyadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - spring-cloud-network

  identity-service:
    build: ./identity-service
    container_name: identity-service
    image: identity-service:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL
    depends_on:
      - postgres
    networks:
      - spring-cloud-network

  common-service:
    build: ./common-service
    container_name: common-service
    image: common-service:latest
    ports:
      - "8081:8081"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL
    depends_on:
      - postgres
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
