version: "3.8"

services:
  identity-service:
    build:
      context: .
      dockerfile: ./identity-service/Dockerfile
    container_name: identity-service
    image: identity-service:latest
    ports:
      - "8081:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - spring-cloud-network

  common-service:
    build:
      context: .
      dockerfile: ./common-service/Dockerfile
    container_name: common-service
    image: common-service:latest
    ports:
      - "8082:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge