global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []

scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets:
        - 'collector:8888'

  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: backend-app
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets:
        - localhost:8080
        - 0.0.0.0:8080

  - job_name: backend
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8080']